engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
    config:
      languages:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"